### ISSUE TITLE
Error when deployed from Windows

### ISSUE THREAD

**Issue by paulkamau2015** [mnapoli/bref#80] opened 2018-10-30 02:30 UTC
After a successful completion of the entire Laravel set up and receiving my API endpoints when running "`vendor/bin/bref deploy`", I keep getting the following error when hitting my endpoint: 

```
{
"message": "Internal server error"
}
```
The best thing i can find in the logs is this: 

`Process exited before completing request

`Any ideas to fix this?

**Comment by mnapoli** [comment] 2018-10-30 09:14
Hi, you will need to have a look into the logs on cloudwatch (or using `vendor/bin/bref logs`).

**Comment by mnapoli** [comment] 2018-11-05 14:12
@g87andres is it with Laravel too? Have you changed `serverless.yml` or `handler.js` in any way? What is your Bref version?

Please try removing the `.bref` directory and try deploying again.

**Comment by paulkamau2015** [comment] 2018-11-05 17:46
@mnapoli and @g87andres. I have the same cloudwatch error logs as well. After researching online, it has something to do with the read permissions on the zip file generated and upload to S3. 

I am using a windows machine. Is there a way to ensure the zip file has the correct read permissions on it? 

Some of the suggestions I found were adding the "mode" property to the severless.yml file for this: 
 
```
mode: 0644 # change mode for all files
 include:
    - handler.js
    - bref.php
```

**Comment by mnapoli** [comment] 2018-11-05 18:49
Oh that's interesting, @g87andres are you on Windows too?

@paulkamau2015 you can edit the `serverless.yml` file and try that?

**Comment by paulkamau2015** [comment] 2018-11-06 01:08
@mnapoli , I did try updating the serverless.yml but it did not work, unfortunately. the same error appears. I also tried to set the permissions to "everyone" on S3 for the zip file but that did not work as well.

**Comment by g87andres** [comment] 2018-11-06 05:16
Yes I am on windows as well. If I deploy the same code via a Linux VM everything works fine.

Very odd

**Comment by paulkamau2015** [comment] 2018-11-06 15:33
Is there anything that can be done for people with windows machines? I would really love to get this working.

**Comment by mnapoli** [comment] 2018-11-06 15:40
@paulkamau2015 I have no idea as I do not work with Windows. We have to find a solution together :) Have you looked into the "serverless" project issues to see if there's an open issue there? Feel free to link interesting issues/links here so that others can investigate too.

**Comment by slootjes** [comment] 2018-11-09 21:50
This is because the php binary needs to be given execute permissions which Windows is unable to do. The solution would be to deploy from a VM or container.

**Comment by mnapoli** [comment] 2018-11-09 22:30
Right that seems like a lost cause, though I'm not a Windows expert :/

See https://github.com/adieuadieu/serverless-chrome/issues/21 they seem to have the same problem (I guess they deploy the Chrome binary, and if you deploy from Windows the binary is missing the execution permissions).

Help is welcome!

**Comment by MickaelTH** [comment] 2018-12-05 04:14
Did more testings about this error using the Bref readme as sample.

Test 1
create in Windows and deploy from Windows => **Internal server error**

Test 2
create in Windows, use VirtualBox with LinuxMint with shared folder, deploy from Linux => **Internal server error**

Test 3
create in Windows, use VirtualBox with LinuxMint with shared folder, copy files into linux, deploy from Linux => **Internal server error**

Test 4
create in Linux, deploy from Linux => **Success**

Will continue to investigate as it is important to be able to use Bref from any OS to help having more people interested in it. But for now the best for Windows user (like me) is to develop in dual-boot or use VirtualBox with Ubuntu or LinuxMint or any other flavor to directly develop your app.

**Comment by MickaelTH** [comment] 2018-12-05 13:20
More investigations by comparing a ZIP from Windows not working and a ZIP from Linux working.

I think the issue is in the exec flag not set from a Windows ZIP on the php binary and the opcache modules.

@mnapoli Should we continue to investigate this issue or will it be resolved if you change the logic to use a layer in lambda?

![2018-12-05 003372](https://user-images.githubusercontent.com/26375917/49515914-c959fc00-f8ca-11e8-8c21-a0527ab2902f.png)

![2018-12-05 003373](https://user-images.githubusercontent.com/26375917/49515915-c959fc00-f8ca-11e8-8c1d-df8968ca2037.png)

![2018-12-05 003374](https://user-images.githubusercontent.com/26375917/49515917-c959fc00-f8ca-11e8-80d0-e35458f701fa.png)

**Comment by mnapoli** [comment] 2018-12-05 13:21
> @mnapoli Should we continue to investigate this issue or will it be resolved if you change the logic to use a layer in lambda?

Yes so in #99 I check out AWS SAM and this is a serious alternative to Serverless. I think it's very likely v0.3 of Bref goes that way. However I don't know if SAM works on Windows?

https://github.com/mnapoli/bref-bootstrap-benchmarks uses SAM btw if you want to try it out.

**Comment by MickaelTH** [comment] 2018-12-19 17:19
@mnapoli I did not try the 0.3 yet, but for what I read this should resolve this issue once and for all. Correct?

**Comment by mnapoli** [comment] 2018-12-19 17:33
At the moment it's not stable at all. But I don't know if AWS SAM is compatible with Windows. If it is then yes it will probably work much better.

**Comment by mnapoli** [comment] 2019-01-05 21:32
AWS SAM seems to be compatible with Windows so v0.3 should solve the problem (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-windows.html).

**Comment by mnapoli** [comment] 2019-01-19 11:57
I'll close this for now since 0.3 *should* fix this. If there are still issues let's open a separate issue because the whole discussion here will be obsolete (v0.3 changes a lot of things regarding deployment).

**Closed by mnapoli** 2019-01-19 11:57 UTC
Labels: bug, help wanted
